kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgdata-master-pvc
  labels:
    app: {{ .Values.appName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi