kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-pv
  labels:
    app: {{ .Values.appName }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pv0001/
