apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    app: {{ .Values.appName }}
data:
  POSTGRESQL_REPLICATION_PASSWORD: c2ltcGxlcmVwbGljYXBhc3N3b3Jk
  POSTGRESQL_PASSWORD: c2ltcGxlcGFzc3dvcmQ=