apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: {{ .Values.appName }}
data:
  SIMPLE_APP_DB_HOST: {{ .Values.app.db_host }}
  SIMPLE_APP_DB_PORT: {{ .Values.app.db_port | quote }}
  SIMPLE_APP_DB_NAME: {{ .Values.app.db_name }}
  SIMPLE_APP_DB_USER: {{ .Values.app.db_user }}
  SIMPLE_APP_SMTP_SERVER: {{ .Values.app.smtp_server }}