apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: {{ .Values.appName }}
data:
  POSTGRESQL_REPLICATION_MODE: {{ .Values.app.replication_mode }}
  POSTGRESQL_REPLICATION_USER: {{ .Values.app.replication_user }}
  POSTGRESQL_MASTER_HOST: {{ .Values.app.master_host }}